In [1]:
import sys
sys.path.append('../')
from  mongo.lib.mongo_db  import db_conn
import pandas as pd
import numpy as np
from pyecharts import Bar,configure,Pie
import time
from es_select import ES
import itertools

In [2]:
BEGIN_DATE='20181004'
END_DATE='20181005'

In [3]:
def date_to_time(date):
    timeArray = time.strptime(date, "%Y%m%d")
    time_semp = time.mktime(timeArray)
    return time_semp   # 2013
def date_to_date(date):
    timeArray = time.strptime(date, "%a %b %d %H:%M:%S %Y")
    time_semp = time.strftime("%Y%m%d%H%M%S", timeArray);
    return time_semp   # 2013

def time_to_today(timeStamp):
    timeArray = time.localtime(int(timeStamp))
    timeArray =time.strftime("%Y-%m-%d %H:%M:%S",timeArray)
    return timeArray   # 2013

## 1、查询20181106日联通出现 5017 （尊敬的客户您好，系统检测您的访问过于频繁，为保障您的账户安全请明天再试。）

In [4]:
data=db_conn.sid_info.find({"end_time":{'$gte':date_to_time(BEGIN_DATE),'$lte':date_to_time(END_DATE)},'status':5017})
data1=list(data)

In [5]:
data1_rpt_pd=pd.DataFrame(x for x in data1)

## 2、将代理信息和目标URL取出，统计请求次数、使用代理数量、代理去重列表

In [6]:
def get_proxy(data1_rpt_pd):
    all_sid_http_proxy=[]
    for sid in data1_rpt_pd.sid.values.tolist():
        es=ES(END_DATE)
        one_sid_http_proxy={}
        #print (sid)
        ret_list=es.get_all_ret(sid)
        #print(len(ret_list))
        one_sid_http_proxy['sid']=sid
        one_sid_http_proxy['tel']=data1_rpt_pd.loc[data1_rpt_pd.sid.values==sid,'tel'].values.tolist()[0]
        one_sid_http_proxy['status']=data1_rpt_pd.loc[data1_rpt_pd.sid.values==sid,'status'].values.tolist()[0]
        one_sid_http_proxy['http_proxy']=[]
        one_sid_http_proxy['url_base']=[]
        one_sid_http_proxy['dates']=[]
        for i,one_http in enumerate(ret_list):
            one_sid_http_proxy['http_proxy'].append(one_http['_source']['MSG']['proxies']['http'].replace('http://','').split('.')[0])
            one_sid_http_proxy['url_base'].append(one_http['_source']['MSG']['url'])
            one_sid_http_proxy['dates'].append(date_to_date(one_http['_source']['DATETIME']))
        l = [(k, len(list(g))) for k, g in itertools.groupby(one_sid_http_proxy['http_proxy'])]
        one_sid_http_proxy['http_req_count']=l
        one_sid_http_proxy['req_count']=len(ret_list)
        one_sid_http_proxy['http_unique']=list(set(one_sid_http_proxy['http_proxy']))
        one_sid_http_proxy['http_unique_count']=len(one_sid_http_proxy['http_unique'])
        all_sid_http_proxy.append(one_sid_http_proxy)
    return all_sid_http_proxy

In [7]:
all_sid_http_proxy=get_proxy(data1_rpt_pd)

In [8]:
all_sid_http_proxy_pd=pd.DataFrame(x for x in all_sid_http_proxy)

In [9]:
all_sid_http_proxy_pd=all_sid_http_proxy_pd.fillna(0)

## 3、将数据按照手机号码组织，并获取单个客户的请求此次，使用的代理数量

In [10]:
def chain_l(l):
    ret_dict={}
    for one in l:
        if one[0] in ret_dict:
            ret_dict[one[0]]+=one[1]
        else:
            ret_dict[one[0]]=one[1]
    return ret_dict

In [11]:
import itertools
def get_new_tel_list(all_sid_http_proxy_pd):
    new_tel_list=[]
    for tel in all_sid_http_proxy_pd.tel.unique().tolist():
        new_tel_dict={}
        tmp=all_sid_http_proxy_pd.loc[all_sid_http_proxy_pd.tel.values==tel,['tel','req_count','http_req_count','http_unique_count','http_unique']]
        tmp=tmp.fillna(0)
        #print(tmp.shape)
        new_tel_dict['tel']=tel
        new_tel_dict['req_count']=tmp.req_count.values.sum()
        #print(tmp.http_req_count.values.tolist())
        l=list(itertools.chain(*tmp.http_req_count.values.tolist()))
        l_dict=chain_l(l)
        new_tel_dict['http_req_count']=tuple(l_dict.values())
        new_tel_dict['http_unique_count']=tmp.http_unique_count.values.sum()
        new_tel_dict['http_unique']= tuple(l_dict)
        new_tel_list.append(new_tel_dict)
    new_tel_pd=pd.DataFrame(x for x in new_tel_list)
    return new_tel_pd

In [12]:
new_tel_pd=get_new_tel_list(all_sid_http_proxy_pd)

## 4、当天只使用同一个代理但是被封的客户

In [13]:
filte=np.logical_and(new_tel_pd.http_unique_count.values==1,True)
tmp_1=new_tel_pd.loc[filte,['tel','req_count','http_unique_count','http_unique']]

In [14]:
tmp_1

             tel  req_count  http_unique_count   http_unique
0    17677563578         22                  1  (squidsz67,)
1    18576382114         22                  1  (squidsz65,)
2    18628456345         22                  1  (squidsz63,)
3    13162561856         20                  1  (squidsz46,)
5    18555552274         22                  1  (squidsz43,)
7    13067815188         22                  1  (squidsz87,)
8    13249091588         22                  1  (squidsz81,)
9    17600511569         20                  1  (squidsz79,)
10   18502867720         22                  1  (squidsz80,)
11   15678504900         22                  1  (squidsz78,)
12   17585862065         22                  1  (squidsz76,)
15   15591055019         22                  1  (squidsz74,)
16   15514371930         22                  1  (squidsz40,)
18   18583615160         20                  1  (squidsz30,)
19   18602468235         22                  1  (squidsz27,)
20   18610527265         23                  1  (squidsz26,)
23   18677203197         20                  1  (squidsz23,)
24   15655514444         22                  1  (squidsz18,)
29   13054513095         23                  1  (squidsz08,)
30   18585769798         22                  1  (squidsz07,)
31   13145961543         22                  1  (squidsz06,)
32   15521133887         20                  1  (squidsz70,)
34   15617878017         20                  1  (squidsz68,)
35   15522163854         22                  1  (squidsz64,)
36   15676395532         22                  1  (squidsz62,)
38   18576012376         24                  1  (squidsz61,)
39   15681000022         20                  1  (squidsz49,)
40   17620805172         22                  1  (squidsz48,)
41   15550975210         22                  1  (squidsz46,)
43   18642887198         22                  1  (squidsz89,)
..           ...        ...                ...           ...
641  18686235123         22                  1  (squidsz06,)
642  13045670001         20                  1  (squidsz05,)
643  18562792456         22                  1  (squidsz48,)
644  18579811512         22                  1  (squidsz49,)
645  13035028306         22                  1  (squidsz47,)
646  18684177543         29                  1  (squidsz41,)
647  18653371003         22                  1  (squidsz89,)
649  15563293771         22                  1  (squidsz32,)
650  17607602756         27                  1  (squidsz30,)
651  15667257008         27                  1  (squidsz31,)
652  13266513012         22                  1  (squidsz67,)
653  13132994096         26                  1  (squidsz48,)
654  17692633137         22                  1  (squidsz89,)
658  15606687320         22                  1  (squidsz42,)
660  18622998058         22                  1  (squidsz32,)
661  17695169440         35                  1  (squidsz67,)
662  15615973828         22                  1  (squidsz47,)
663  18655986088         22                  1  (squidsz32,)
664  18580589240         22                  1  (squidsz05,)
665  17623333293         38                  1  (squidsz89,)
666  17630340994         22                  1  (squidsz47,)
667  18559000901         26                  1  (squidsz32,)
668  18523083441         22                  1  (squidsz05,)
669  15522476970         22                  1  (squidsz49,)
671  17664179391         22                  1  (squidsz47,)
672  18639888315         40                  1  (squidsz49,)
674  15509568301         36                  1  (squidsz47,)
675  13027967400         28                  1  (squidsz42,)
677  15604004002          1                  1  (squidsz37,)
678  13002330303         45                  1  (squidsz47,)

[530 rows x 4 columns]

### 将出现5017的客户按照手机号进行反查，查看当天调用量

In [15]:
data=db_conn.sid_info.find({"end_time":{'$gte':date_to_time(BEGIN_DATE),'$lte':date_to_time(END_DATE)},'tel':{'$in':tmp_1.tel.values.tolist()}})
data2=list(data)
data2=pd.DataFrame(x for x in data2)
one_sid_http_proxy=get_proxy(data2)
one_tel_http_proxy_pd=pd.DataFrame(x for x in one_sid_http_proxy) 
one_tel_http_proxy_pd=get_new_tel_list(one_tel_http_proxy_pd)

In [16]:
one_tel_http_proxy_pd.loc[:,['tel','req_count','http_unique_count','http_unique']]

,tel,req_count,http_unique_count,http_unique
0,13002330303,45,1,"(squidsz47,)"
1,13003096351,22,1,"(squidsz11,)"
2,13006486555,22,1,"(squidsz50,)"
3,13011597144,22,1,"(squidsz86,)"
4,13013093266,22,1,"(squidsz09,)"
5,13013389608,22,1,"(squidsz72,)"
6,13013457700,22,1,"(squidsz20,)"
7,13016072160,22,1,"(squidsz02,)"
8,13025725285,23,1,"(squidsz28,)"
9,13026990346,25,1,"(squidsz22,)"
10,13027537067,22,1,"(squidsz77,)"
11,13027677468,20,1,"(squidsz79,)"
12,13027719222,22,1,"(squidsz63,)"
13,13027904229,24,1,"(squidsz33,)"
14,13027967400,28,1,"(squidsz42,)"
15,13030381117,20,1,"(squidsz44,)"
16,13033320861,22,1,"(squidsz21,)"
17,13035028306,22,1,"(squidsz47,)"
18,13039353822,25,1,"(squidsz06,)"
19,13042008058,25,1,"(squidsz82,)"
20,13042042356,26,1,"(squidsz85,)"
21,13045670001,20,1,"(squidsz05,)"
22,13048766846,22,1,"(squidsz46,)"
23,13049340911,20,1,"(squidsz02,)"
24,13053529989,22,1,"(squidsz42,)"
25,13054513095,23,1,"(squidsz08,)"
26,13055869010,22,1,"(squidsz11,)"
27,13058163704,22,1,"(squidsz01,)"
28,13065711121,23,1,"(squidsz75,)"
29,13066761997,22,1,"(squidsz20,)"
...,...,...,...,...
500,18678917073,22,1,"(squidsz44,)"
501,18680200502,22,1,"(squidsz82,)"
502,18682052135,22,1,"(squidsz84,)"
503,18682890080,22,1,"(squidsz16,)"
504,18683698379,22,1,"(squidsz43,)"
505,18684177543,29,1,"(squidsz41,)"
506,18685014053,50,1,"(squidsz27,)"
507,18685061030,23,1,"(squidsz18,)"
508,18685592287,110,1,"(squidsz02,)"
509,18685671344,22,1,"(squidsz30,)"
510,18685745571,22,1,"(squidsz36,)"
511,18685935221,22,1,"(squidsz05,)"
512,18686235123,22,1,"(squidsz06,)"
513,18687052387,54,3,"(squidsz05, squidsz23, squidsz71)"
514,18687125078,23,1,"(squidsz74,)"
515,18687578222,22,1,"(squidsz31,)"
516,18687768079,22,1,"(squidsz46,)"
517,18688359934,16,1,"(squidsz42,)"
518,18688739130,22,1,"(squidsz66,)"
519,18688827862,22,1,"(squidsz71,)"
520,18689324329,21,1,"(squidsz73,)"
521,18690263908,25,1,"(squidsz88,)"
522,18690662569,22,1,"(squidsz08,)"
523,18690826907,22,1,"(squidsz79,)"
524,18691127506,22,1,"(squidsz36,)"
525,18693612323,47,2,"(squidsz63, squidsz77)"
526,18697114889,22,1,"(squidsz17,)"
527,18697162850,22,1,"(squidsz89,)"
528,18697982239,22,1,"(squidsz24,)"
529,18698420349,22,1,"(squidsz40,)"

### 接下来分析 代理 squidsz40，在这次请求前后是否正常

In [19]:
def sid_get_err_code(sid):
    data=db_conn.sid_info.find_one({"sid":sid,},{'_id':0,'status':1})
    return data.get('status',1)

In [29]:
def sid_get_flow_type(sid):
    data=db_conn.sid_info.find_one({"sid":sid,},{'_id':0,'tel_info':1,'status':1})
    return data['tel_info']['flow_type']

In [61]:
def anly_one_ip_proxy(one_ip_proxy):
    es=ES(END_DATE)
    proxy_ret=es.get_proxy_ret(one_ip_proxy)
    del es
    one_sid_http_proxy_list=[]
    for one in proxy_ret:
        one_sid_http_proxy={}
        one_sid_http_proxy['http_proxy']=one_ip_proxy
        one_sid_http_proxy['url_base']=(one['_source']['MSG']['url'])
        one_sid_http_proxy['dates']=(date_to_date(one['_source']['DATETIME']))
        one_sid_http_proxy['sid']=((one['_source']['MSG']['sid']))
        one_sid_http_proxy_list.append(one_sid_http_proxy)
    one_sid_http_proxy_pd=pd.DataFrame(x for x in one_sid_http_proxy_list)
    #one_sid_http_proxy_pd.groupby('sid')['http_proxy'].size().reset_index()
    
    ip_proxy_sort_pd=one_sid_http_proxy_pd.groupby('sid')['dates'].max().reset_index().sort_values(by="dates")
    ip_proxy_sort_pd_t=one_sid_http_proxy_pd.groupby('sid')['http_proxy'].size().reset_index()
    ip_proxy_sort_pd=pd.merge(ip_proxy_sort_pd,ip_proxy_sort_pd_t,on=['sid'],how='left') 
    ip_proxy_sort_pd['status']=ip_proxy_sort_pd.sid.map(sid_get_err_code)
    ip_proxy_sort_pd['flow_type']=ip_proxy_sort_pd.sid.map(sid_get_flow_type)
    print(ip_proxy_sort_pd.http_proxy.sum())
    return ip_proxy_sort_pd.loc[ip_proxy_sort_pd.flow_type.values=='10010',:]

In [62]:
anly_one_ip_proxy('http://squidsz40.dianhua.cn:8080')

2652

,sid,dates,http_proxy,status,flow_type
3,SIDb9a1c6d7669049f0b5646a3943eeaaec,20181004080134,2,0,10010
7,SID0b0cb5bbd96c4d46b3c158a7f52b4300,20181004094450,2,4999,10010
11,SID74c453c9f00b40439b1e2eab25b848bb,20181004102022,6,4999,10010
16,SIDe491225eb9a849929ae9846d839f5b08,20181004111852,25,0,10010
21,SID4cc78e03cc5b4d97b2186f161983141c,20181004123517,7,0,10010
25,SID5bcad7c1f41f49ec8c36496f9d90d1b4,20181004132336,34,0,10010
28,SID7de7a31c3b004d8987f41377e3cbf266,20181004141434,60,0,10010
31,SIDecb2ff3573a54e13a695d090b0758967,20181004150444,62,0,10010
34,SIDba4307cc9e7b4cf78809cfc764d7c3e3,20181004151732,2,0,10010
37,SID94e751135834464bade437fb56dfed12,20181004152648,29,0,10010
40,SIDebbff478a11545eb9d093fa16b33f4af,20181004153218,27,0,10010
44,SIDd67faedba9e245ea88cf41681498d870,20181004153710,23,0,10010
46,SIDd1faea86659848829d1b07d71df6957c,20181004154042,2,0,10010
50,SID2e1d3264de924d2585977f0bc82ba981,20181004154712,51,0,10010
53,SID06ed0c92a915474abe0b6e70682908e1,20181004155250,22,0,10010
57,SID06af3391994243839b302795fb30b4ef,20181004160109,2,0,10010
59,SID3e07acaf74e143ba800eb33f37c61345,20181004160758,31,0,10010
62,SID1b147b6da9e84db0a50ddfa47805e25c,20181004161730,12,0,10010
66,SID32aa6755a2334a038b7811c448be7916,20181004162851,36,0,10010
68,SID29c4bf8dfa0244988c50b18bc6c82906,20181004163927,16,0,10010
73,SID678971fb3a8d4d649683f8f5154fcc66,20181004165434,29,0,10010
76,SIDc132db330bbc4721bd63d4ef5267d9d2,20181004170505,28,0,10010
79,SID08e2c8bc627c47f29af2d6a2e225dfc3,20181004171710,22,5017,10010
82,SIDae4bdc32e3b547ce91a3a1d267821fb9,20181004172858,2,5017,10010
86,SID90a73681bbe146a3ad98e1560a49858f,20181004173928,6,4999,10010
88,SID1be1021058944ceabeecb9d769833e5d,20181004175158,46,0,10010
93,SIDe297b4c1ee44495f8c0d843dca267ed5,20181004181206,7,3003,10010
96,SID02fe68a7fcca4480b650da23921f6ef7,20181004182736,24,0,10010
100,SIDb898f23f1ab84b8a92aaa665425ff472,20181004184829,23,5017,10010
103,SIDbbf7b388c1a644d69156f9954ef5f2b9,20181004190511,2,3003,10010
107,SID301a6d283d234cc2854dbbc774c5714b,20181004192751,3,5017,10010
110,SID93cec3bcea41469a93b9a1ea3bad65e4,20181004194829,25,5017,10010
113,SIDff025b00c7da4b6ba6c567bab0717b2f,20181004201019,25,5017,10010
116,SIDaf3893a0ffd940a4bc6d2719cf9d924b,20181004203022,23,5017,10010
119,SIDc6307f45707d444ea6450ff8dc1e74e5,20181004204842,22,5017,10010
122,SID4280f2e1222a4df8bec29c980354ad19,20181004210901,23,5017,10010
125,SID12509f41a6334ba99c1755317a86e014,20181004212807,7,4116,10010
128,SIDf2f7c6c2415d41d5b17b104ebc3f3595,20181004214957,22,5017,10010
131,SID948a1991f210407c9873175a20cc2428,20181004221247,22,5017,10010
134,SIDbc12bbbaf37642afb7ff79759b705016,20181004223101,2,4999,10010
136,SIDb5fc531889a546df8ffcccc014dfbc2a,20181004224815,22,5017,10010
139,SIDf3f5d5d6b8b2449db2301a1159f6da09,20181004230617,3,3003,10010
142,SID97fd699dd90b44da93186f603e720a67,20181004232609,26,5017,10010
145,SID9acc7cf172b94d6a8a61d1358a0ea88b,20181004234645,22,5017,10010

In [63]:
anly_one_ip_proxy('http://squidsz08.dianhua.cn:8080')

3219

,sid,dates,http_proxy,status,flow_type
5,SID9c921194d9704069ac24ade1aee92caf,20181004091601,41,0,10010
9,SID2e95712fa82b41caa6b7d2e9bd96e96a,20181004095642,27,0,10010
14,SIDdb3df09518de484f946816bf6ee269cc,20181004105016,24,0,10010
18,SIDed00993c454a44ebaea2f3b457d67104,20181004115923,23,0,10010
23,SID51ab7ff5eeef4b9a8dacbb388983ea8e,20181004130439,39,0,10010
26,SIDfc84b084673d4a3abe55e3b467280e90,20181004135420,22,0,10010
31,SIDece859927ab147f9940546aedbd0cf62,20181004144721,28,0,10010
34,SID15db2ceddf044751965e63b8dc9ccd95,20181004151142,20,0,10010
36,SID21e9481a79ce40a79609d5bc9bae21f3,20181004152356,7,0,10010
43,SIDe297b4c1ee44495f8c0d843dca267ed5,20181004153817,8,3003,10010
44,SIDd292fa8aaf154b31ba85dc14d90a1f3e,20181004153859,2,0,10010
47,SID36ad2bdd7d1c409cb3c2f455a4270458,20181004154441,32,0,10010
50,SID9c1ade833d71463d9246e94aa79666a1,20181004154855,7,4003,10010
55,SIDa7a69a52cb0846659d645a89d262a109,20181004155922,24,0,10010
59,SID61ebe901943640f0a4afa57bb64a4e7a,20181004161305,22,0,10010
63,SIDc80cd29914b14ba09c514896bb14bf55,20181004162615,37,0,10010
66,SIDe6dfb7d7cdb349ae818666e55ca0fd4a,20181004163347,2,0,10010
70,SIDcda73fb3207f4477ad68deb7ae4a8a2b,20181004165024,69,0,10010
75,SID50256cb74c034a1c81285e0675f5dac5,20181004170503,65,0,10010
77,SIDf8daaa1aebbc4c1d895cfd244fd0e432,20181004171309,29,0,10010
80,SID7c83aed1025b4fe082c2e4e816c088f2,20181004172346,6,5017,10010
84,SID9db77236e3df474f92410bab46cc9dcd,20181004173624,32,0,10010
86,SID0263799635724e9eaea00f8064622b7f,20181004174751,48,0,10010
90,SID7530c3cbb12f4aed827f7e844cf0a997,20181004180518,33,5017,10010
91,SID464d08d65c2c43ff905453754e5719c2,20181004180705,1,5017,10010
93,SIDb722581cbfee4077a1525ec4647c1e22,20181004181837,22,5017,10010
97,SID7ffe7f6a1ab447f3a395e561d2a0b0f3,20181004183833,22,5017,10010
100,SIDba93e11755ff4976ab1edd932f04f1ef,20181004185743,5,0,10010
104,SIDf7c95810b1484dbd8c07a52129ec683e,20181004191840,3,3003,10010
107,SID0fbb8bc476cc49a98830dfb25078c5d7,20181004193945,23,0,10010
110,SID6ca397321cc040eb888f9c5156a2c784,20181004195841,22,5017,10010
114,SID253a9038c7d74539b54b28920e330eb5,20181004202124,17,5017,10010
117,SID10a4c90beb7649e89b0dde6c4cd752ad,20181004203907,2,4999,10010
120,SID71246d2e0875489686c734867b6b1890,20181004210149,5,5017,10010
123,SID3c02647c119e4facacf5cd6094457f1c,20181004212020,22,5017,10010
126,SID963e2e90b2924f59a18de5885bf32c04,20181004213926,18,0,10010
129,SID7c6ffa4a4ccf4543b92ad2339bf39cd7,20181004220501,8,4999,10010
132,SID1ddfe5338fd7486585c9e3cf53653cec,20181004222355,3,0,10010
134,SIDc9fea9da0d864095b03c73cd9960e2dd,20181004224145,6,0,10010
137,SID75b3948201e74832bac05c972a82bb02,20181004225930,20,0,10010
140,SIDa84d7c84dd39488e8b54bc48fd4ad4e5,20181004231903,2,5017,10010
143,SIDe1f8f2e93af8419390c2fc5c2fc8c936,20181004234039,23,5017,10010

In [64]:
anly_one_ip_proxy('http://squidsz09.dianhua.cn:8080')

3029

,sid,dates,http_proxy,status,flow_type
2,SIDafd489cbcf42473f93fbb2fd0435be7a,20181004034640,2,0,10010
6,SIDb3be7b43ab344dc8afe2e491649e77de,20181004091620,28,0,10010
10,SIDc8c6095afd524a45aa35f9b7489394c3,20181004095647,21,0,10010
14,SID130ca38afe474da2ae7977078a393b90,20181004104945,5,0,10010
19,SIDfdf5d1483be349da9922a284f290f074,20181004115825,2,4999,10010
24,SID65fdb51fdd1f40be9e40a38746c16871,20181004130605,144,0,10010
28,SID713172485ede42738fa37a18f4df5d28,20181004135537,75,0,10010
32,SID2f368caf36cf46028bf3bb725d3e349d,20181004144626,2,0,10010
35,SID1a9feb6d5ca54e8f9f18c604a502af39,20181004151155,26,0,10010
38,SID61a8328bb1ae43928c0999805e74ae62,20181004152451,40,0,10010
41,SIDc41a005f23504bc0a4521e7416151c27,20181004152954,30,0,10010
44,SID80ae530ea70c4480a7a4112dbfba0e92,20181004153525,28,0,10010
48,SID421b6bccd060427ab20577760d23474f,20181004154025,38,0,10010
50,SID177dfe3d43794a88a8d91b69dd2b3133,20181004154445,23,0,10010
53,SID5d6cf09803614710b46d91be3fa06171,20181004154950,52,0,10010
58,SID03fa6c7a61de4273b032bd3b8a1e73f2,20181004155905,34,0,10010
61,SID6cd5d6bef1a04800a0853aa16143029f,20181004160706,8,5017,10010
63,SIDd7482e43587548898502313af023911e,20181004161354,56,0,10010
67,SID1515499fda30401383bdd7094773ec6b,20181004162457,16,0,10010
70,SID9b8ce3f7c19d442abfb806e7aadf4f9d,20181004163518,7,3003,10010
74,SID3126faecc3924fe4a95bbc782a97732a,20181004164936,7,5017,10010
78,SID4be73f0cb6924fd3adda338f8a8c2b59,20181004170026,2,0,10010
82,SID02601c119f084ba19290a208b13eb485,20181004171734,23,0,10010
85,SID5d467594fdb1491398f7f27dc6e13c83,20181004172503,21,0,10010
87,SIDc72c62f6d6f3491b97cdd33c69792636,20181004173108,1,0,10010
88,SID973e95f9ac1e4efd96bed47453d1d517,20181004173546,22,0,10010
91,SID1ced74ee0e374627a813c9f0638146e5,20181004174637,2,5017,10010
95,SID0b5e6feac5354dac9a422d7dd98302b3,20181004180416,25,5017,10010
98,SIDae4bdc32e3b547ce91a3a1d267821fb9,20181004181819,22,5017,10010
102,SID9739c847d60b4864972bc90f7eb97dfe,20181004183825,7,0,10010
105,SID8896b059f5254ab1ba1d79b299da4740,20181004185828,14,0,10010
109,SID76c5adc8f0b44e15b62348aa7343d2a4,20181004191921,7,5017,10010
113,SID2d951dabedeb4d83883971d86a10c884,20181004193952,7,5017,10010
116,SIDd5d74adcb3864cd385d71401985a395a,20181004195817,22,5017,10010
119,SID10a4c90beb7649e89b0dde6c4cd752ad,20181004202155,6,4999,10010
122,SIDa9a9869b357b48f0bdf7cdfdf845cde9,20181004204033,22,5017,10010
125,SIDba9d252b017749f79c73ec15b900f57a,20181004210409,24,5017,10010
128,SIDfb5c8f68f2934a5986bdb00f3ba4352c,20181004211956,4,4999,10010
131,SIDd09f7f86463746498f1a8bd36c59c952,20181004213945,22,5017,10010
134,SID2ad7ed050e904d02818ccec1b300134d,20181004220510,22,5017,10010
137,SID582539c03ba6424ca8d03d3f305d6cd6,20181004222401,3,5017,10010
139,SID4bffb014a25e45dd83859bbfbc941994,20181004224201,3,0,10010
143,SIDf02cb7e4061f4439af3720c72850cbf0,20181004230546,19,0,10010
145,SID426763acace745ad9d299fbb92a11beb,20181004231940,7,5017,10010
148,SID705ca1f7c826449b88b91667f9a97454,20181004234116,22,5017,10010

In [65]:
anly_one_ip_proxy('http://squidsz32.dianhua.cn:8080')

2931

,sid,dates,http_proxy,status,flow_type
2,SID830e7f79b6d9409e9e011bb4a9e1059a,20181004073514,44,0,10010
7,SID23f540e072c240d099e901a8e3d3450f,20181004094339,33,0,10010
11,SID3d011f6ac6d24a768810b653a86da433,20181004101321,35,0,10010
15,SID4d098917d88341e4a3cdca6d7c762c3d,20181004110559,5,0,10010
20,SIDeafb9b27d4d74a658cb1b15f88b77fea,20181004122510,33,0,10010
24,SIDd8d8a5db13384af1a34d789dd053589c,20181004131832,2,3003,10010
28,SID3aa4d32395c2496b87e129f4ac5016a4,20181004140849,32,0,10010
32,SIDc2d2356d7beb4c2c844b7e6373633483,20181004150000,2,4999,10010
35,SIDa477c3a82bb448d4afbaa96d0d66039b,20181004151810,64,0,10010
38,SIDab536896ddbe41cc9ad7058a49771926,20181004152642,47,0,10010
41,SID31033fe1cd0f4d34948e1adf549279b0,20181004153214,44,0,10010
44,SID17052b83d8e04426a7175f90af8fe5fe,20181004153659,31,0,10010
47,SIDd9d368b998524d37b1ffc365c2f428be,20181004154130,26,0,10010
49,SIDb89cae277de44a03bad77fd4941242df,20181004154528,38,0,10010
53,SIDfbdc6c4d0a7b427bbaf52137cbffc183,20181004155218,23,0,10010
56,SID172fcc65adb847c189ad805234d55801,20181004160040,2,0,10010
59,SID79781507b6914bcea9ab9755c2007920,20181004160737,43,0,10010
62,SID0aea47f5e60e4a81a9e77b207f4b403e,20181004161706,26,5017,10010
66,SID302b4cfc199d436f9311f9ebd8b19f0a,20181004162823,22,5017,10010
69,SID982cb81c983149b09ca2fd9ce6454649,20181004163852,22,5017,10010
74,SID96e5c10a37a340bb899ce18a98b868f5,20181004165302,7,0,10010
77,SID8ebe5c3309344b8583b09da28b61c53e,20181004170424,22,5017,10010
81,SIDd430de63ba3141bc9331efc1c2c17261,20181004171541,2,5017,10010
84,SIDce47745375f8492c965e9d2fdc144484,20181004172821,28,0,10010
87,SIDde963b5c2d4047219c66b429361eaf84,20181004173843,7,4999,10010
89,SID41fec63e4bb44c6da7e4a9f41c8b9080,20181004175004,7,4003,10010
93,SID3d6a0b0c238844c0a6be4f8f9395a024,20181004180744,20,0,10010
96,SID9a4566b400964dee8212b06d901145a7,20181004182340,22,5017,10010
99,SID62a421a025424c1e9fbaae98fe164f5b,20181004184535,22,5017,10010
103,SIDb03d8a85d49e4a048a9db8254b096634,20181004190452,22,5017,10010
107,SID915e5464b7bc49eba49498f015ca313d,20181004192706,22,5017,10010
110,SID2fa5c9c08f624a4aaeee51f73ea70466,20181004194629,22,5017,10010
113,SID4398a0a9ac5e4258b5483aa3295d9b43,20181004200654,16,0,10010
116,SIDea9694d8e36c4d038edfb64081b3c0b1,20181004202922,7,5017,10010
119,SID8b8bde7b0d9c432b8571dd1d0532a99e,20181004204644,22,5017,10010
122,SID5f0901734ac54591a47ec40c5cd6c04e,20181004210628,20,0,10010
125,SIDfb5c8f68f2934a5986bdb00f3ba4352c,20181004212628,7,4999,10010
128,SID7c6ffa4a4ccf4543b92ad2339bf39cd7,20181004214832,7,4999,10010
131,SID7cbe87b0860d4b8ebd4c0d7e72abfeb9,20181004221048,16,0,10010
133,SID54430ed4312d4dfdb608f49c7f3f3322,20181004222934,3,5017,10010
135,SID8ebe6aa6c4d649daadc4af5fc1fb6640,20181004224659,16,0,10010
138,SID1216c4e777094827b399f417258c3f4d,20181004230508,16,0,10010
141,SID15236cd4ef024d859ee4f4570830882d,20181004232431,7,0,10010
144,SID11766ec2ea2c43d3aa191d96194b1f04,20181004234553,7,0,10010

In [78]:
anly_one_ip_proxy('http://squidsz35.dianhua.cn:8080')

3334

,sid,dates,http_proxy,status,flow_type
2,SID2e08716c19544c9a94278d3f18c0fa80,20181004074055,5,0,10010
7,SID0c6dba40d6c648d080d33ae877042341,20181004094358,30,0,10010
11,SIDa56820de5fa94cb184799af8d16a6e23,20181004101606,43,0,10010
14,SID467c87e1fb214e2ababd7c73110ee5f9,20181004111428,50,0,10010
20,SIDa7d5d21ace064acda8a287884b759edf,20181004123024,33,0,10010
23,SIDd8d8a5db13384af1a34d789dd053589c,20181004132015,3,3003,10010
27,SID09f3697bb883430d91d62b2ff85c5261,20181004141016,2,4999,10010
33,SID01531efed69c4aa8b3767e35e80084c7,20181004151706,8,0,10010
36,SIDb24da78bd565485097f4811a715fb9d4,20181004152653,33,0,10010
39,SID2a07816e1232411ca3d6b4c50e3550f2,20181004153025,2,5017,10010
42,SIDac61cb525fd246fd845dca428aefb9d7,20181004153610,3,0,10010
45,SIDbb84b50798b64550874c62552ab5979e,20181004154119,13,0,10010
48,SID9211795bf9994ebaba4023f2cf014187,20181004154550,46,0,10010
50,SIDf4e50efa3e68482fb735161ee9395334,20181004155216,13,0,10010
56,SID288567dcf92d4e629cb3ad533e4f4f89,20181004160438,32,0,10010
57,SID06d53d5129a145c89ffd6d3c1a5deb90,20181004160729,29,0,10010
60,SIDc68d290f179540e2b75636cccc49d930,20181004161654,32,0,10010
65,SID864b25a9358d43ffb0fe665b604ec601,20181004163009,13,0,10010
67,SIDd32ac905ea9a4f1d89b64b213a5bc143,20181004163908,30,0,10010
72,SID0e66b3375fb1470e9a48c70a59682a0b,20181004165413,23,0,10010
75,SID9b61bb37322b42ec943d8a98e3299b56,20181004170341,2,5017,10010
79,SIDa7e2dc5306744af28e132e47e3ec8f80,20181004171700,16,0,10010
82,SIDe31c17069a2b490cbd996ea4f8bf7529,20181004172917,26,0,10010
84,SID1ced74ee0e374627a813c9f0638146e5,20181004173815,2,5017,10010
87,SID64bdf21cf71c48a3842261952d96919e,20181004175055,24,0,10010
91,SIDcd3966ad39fd4db4a59e187a3f22eac0,20181004181051,28,0,10010
95,SID1152c69a9d2d4cd495d26697826312e7,20181004182645,47,0,10010
98,SID089dd4c79de84bf4be1a85a85ad6230b,20181004184543,7,0,10010
102,SIDbbf7b388c1a644d69156f9954ef5f2b9,20181004190500,4,3003,10010
106,SIDf22a396aff604ec08b97cdb4a81547e8,20181004192805,22,0,10010
109,SID93cec3bcea41469a93b9a1ea3bad65e4,20181004194631,2,5017,10010
112,SID7b627afda48a4d099da7d2e644ccf290,20181004200811,30,0,10010
115,SID4c9125c5b2f341e7a3331966509ec545,20181004203026,7,3003,10010
118,SIDa8f3f4db1a554712b094092c35c518fa,20181004204640,7,4003,10010
121,SIDd681e8e636494d4690035a969b46214f,20181004210917,8,4003,10010
124,SIDd2d16fd7e4ae4107ac2214fa99e96402,20181004212622,23,5017,10010
127,SID5aeac22c7f414351b37e273b08f0b2ff,20181004214943,16,0,10010
130,SID7c6ffa4a4ccf4543b92ad2339bf39cd7,20181004221030,2,4999,10010
132,SIDd5fef593bda14bd59e8aa61358ffd998,20181004223031,3,3003,10010
135,SIDb3555e0999fe46dbbcd46890900a105c,20181004224637,2,5017,10010
138,SID5e94b5825687469d8f910e4a31cc5c47,20181004230611,22,5017,10010
141,SID49f099afae6c4cbc881a7ab7cb18768f,20181004232531,22,5017,10010
144,SID46eaf02dc43f41949fcbf49d318ed9e6,20181004234408,2,5017,10010

#### 出现了请求频繁，该代理之后的其他会话中还是可以正常使用，并爬取成功，有的代理在后续的会话中不再成功。

## 5、使用多个代理被封情况分析
req_count 为请求官网次数

http_req_count 为http_unique中代理对应请求次数

http_unique_count 为使用代理个数

http_unique 为被使用过的代理

### A、使用代理数量超过1个的客户

In [50]:
filte=np.logical_and(new_tel_pd.http_unique_count.values>1,True)
tmp_2=new_tel_pd.loc[filte,['tel','req_count','http_req_count','http_unique_count','http_unique']]
tmp_2

,tel,req_count,http_req_count,http_unique_count,http_unique
4,17638123140,29,"(7, 22)",2,"(squidsz85, squidsz41)"
6,18558422616,23,"(16, 3, 2, 2)",4,"(squidsz90, squidsz83, squidsz84, squidsz86)"
13,13007944252,25,"(3, 22)",2,"(squidsz29, squidsz75)"
14,18529555537,30,"(3, 2, 2, 23)",4,"(squidsz15, squidsz17, squidsz19, squidsz73)"
17,15515995815,36,"(7, 2, 3, 22, 2)",5,"(squidsz20, squidsz35, squidsz31, squidsz38, s..."
21,18595193113,40,"(15, 3, 22)",3,"(squidsz25, squidsz02, squidsz09)"
22,18582883468,26,"(2, 22, 2)",3,"(squidsz16, squidsz24, squidsz22)"
25,18524813889,31,"(7, 24)",2,"(squidsz11, squidsz14)"
26,17629721826,27,"(3, 2, 22)",3,"(squidsz41, squidsz42, squidsz13)"
27,13136305928,27,"(3, 22, 2)",3,"(squidsz01, squidsz10, squidsz03)"
28,17586851595,71,"(19, 19, 2, 7, 24)",5,"(squidsz12, squidsz67, squidsz18, squidsz33, s..."
33,17520318696,43,"(15, 2, 2, 2, 22)",5,"(squidsz69, squidsz71, squidsz36, squidsz39, s..."
37,13173905695,46,"(21, 25)",2,"(squidsz50, squidsz36)"
42,15515666682,35,"(7, 6, 22)",3,"(squidsz85, squidsz87, squidsz45)"
52,13131673087,53,"(5, 6, 2, 7, 6, 2, 25)",7,"(squidsz15, squidsz22, squidsz19, squidsz31, s..."
56,17620606061,37,"(15, 22)",2,"(squidsz71, squidsz64)"
59,15641403063,46,"(21, 25)",2,"(squidsz30, squidsz83)"
60,17640094887,52,"(15, 15, 22)",3,"(squidsz26, squidsz12, squidsz62)"
64,13110973856,37,"(15, 22)",2,"(squidsz21, squidsz66)"
65,13143340908,33,"(7, 2, 24)",3,"(squidsz02, squidsz06, squidsz20)"
68,15653783544,31,"(7, 2, 22)",3,"(squidsz09, squidsz12, squidsz13)"
71,17658603459,59,"(8, 6, 7, 6, 6, 7, 6, 7, 4, 2)",10,"(squidsz73, squidsz47, squidsz05, squidsz48, s..."
73,13261685155,68,"(7, 7, 9, 12, 6, 7, 7, 7, 6)",9,"(squidsz87, squidsz44, squidsz07, squidsz13, s..."
78,17682498323,44,"(15, 2, 2, 3, 22)",5,"(squidsz61, squidsz77, squidsz78, squidsz75, s..."
81,17600202479,40,"(17, 23)",2,"(squidsz48, squidsz70)"
83,18575939342,59,"(10, 2, 8, 2, 29, 8)",6,"(squidsz68, squidsz26, squidsz31, squidsz75, s..."
93,18617072787,33,"(8, 23, 2)",3,"(squidsz30, squidsz37, squidsz34)"
94,17681101870,27,"(4, 23)",2,"(squidsz22, squidsz31)"
96,15656095523,52,"(15, 15, 22)",3,"(squidsz28, squidsz15, squidsz03)"
97,13205818187,37,"(15, 22)",2,"(squidsz26, squidsz90)"
...,...,...,...,...,...
484,13183481129,41,"(2, 17, 22)",3,"(squidsz20, squidsz24, squidsz49)"
488,15566671223,87,"(3, 2, 15, 15, 15, 34, 3)",7,"(squidsz88, squidsz90, squidsz19, squidsz03, s..."
490,15585819425,55,"(30, 25)",2,"(squidsz14, squidsz69)"
492,18630206082,57,"(5, 15, 15, 22)",4,"(squidsz70, squidsz10, squidsz73, squidsz34)"
505,15633770990,37,"(7, 6, 24)",3,"(squidsz16, squidsz21, squidsz82)"
520,15601092016,79,"(7, 8, 7, 7, 9, 6, 6, 9, 7, 11, 2)",11,"(squidsz20, squidsz09, squidsz87, squidsz70, s..."
534,13191985432,39,"(2, 7, 30)",3,"(squidsz42, squidsz86, squidsz44)"
536,13173511137,37,"(15, 22)",2,"(squidsz41, squidsz03)"
551,15577642909,49,"(23, 26)",2,"(squidsz16, squidsz42)"
554,18586835273,38,"(2, 7, 7, 22)",4,"(squidsz40, squidsz30, squidsz36, squidsz09)"
555,18681187010,28,"(6, 22)",2,"(squidsz48, squidsz02)"
562,18593160629,40,"(7, 2, 7, 2, 22)",5,"(squidsz26, squidsz35, squidsz70, squidsz09, s..."
568,18631897051,28,"(4, 23, 1)",3,"(squidsz04, squidsz26, squidsz08)"
583,18629516524,37,"(15, 22)",2,"(squidsz49, squidsz48)"
594,17638345009,73,"(7, 7, 7, 7, 8, 7, 8, 22)",8,"(squidsz20, squidsz87, squidsz49, squidsz31, s..."
598,18582593817,29,"(7, 22)",2,"(squidsz01, squidsz16)"
608,13011584155,69,"(9, 3, 25, 32)",4,"(squidsz42, squidsz13, squidsz82, squidsz26)"
614,18683806286,69,"(27, 42)",2,"(squidsz63, squidsz76)"
616,13227727630,29,"(22, 7)",2,"(squidsz46, squidsz79)"
620,18647511109,65,"(7, 2, 56)",3,"(squidsz73, squidsz78, squidsz81)"
621,17600439098,77,"(10, 7, 7, 8, 6, 8, 15, 8, 6, 2)",10,"(squidsz88, squidsz25, squidsz29, squidsz73, s..."
633,13278676127,35,"(3, 3, 27, 2)",4,"(squidsz24, squidsz37, squidsz86, squidsz32)"
648,18665009230,47,"(5, 2, 2, 38)",4,"(squidsz21, squidsz39, squidsz35, squidsz84)"
655,17677131251,6,"(3, 1, 2)",3,"(squidsz88, squidsz15, squidsz43)"
656,13014271855,25,"(3, 22)",2,"(squidsz64, squidsz06)"
657,18666740667,28,"(6, 22)",2,"(squidsz66, squidsz05)"
659,13208153720,9,"(7, 1, 1)",3,"(squidsz72, squidsz76, squidsz77)"
670,13255692959,29,"(3, 2, 2, 22)",4,"(squidsz13, squidsz23, squidsz27, squidsz42)"
673,15685291014,6,"(2, 2, 2)",3,"(squidsz35, squidsz37, squidsz88)"
676,17608225135,6,"(2, 2, 2)",3,"(squidsz69, squidsz03, squidsz13)"

### B、分析代理总调用次数小于100次的客户

In [51]:
filte=np.logical_and(new_tel_pd.http_unique_count.values>1,new_tel_pd.req_count.values<100)
tmp_3=new_tel_pd.loc[filte,['tel','req_count','http_req_count','http_unique_count','http_unique']]
tmp_3

,tel,req_count,http_req_count,http_unique_count,http_unique
4,17638123140,29,"(7, 22)",2,"(squidsz85, squidsz41)"
6,18558422616,23,"(16, 3, 2, 2)",4,"(squidsz90, squidsz83, squidsz84, squidsz86)"
13,13007944252,25,"(3, 22)",2,"(squidsz29, squidsz75)"
14,18529555537,30,"(3, 2, 2, 23)",4,"(squidsz15, squidsz17, squidsz19, squidsz73)"
17,15515995815,36,"(7, 2, 3, 22, 2)",5,"(squidsz20, squidsz35, squidsz31, squidsz38, s..."
21,18595193113,40,"(15, 3, 22)",3,"(squidsz25, squidsz02, squidsz09)"
22,18582883468,26,"(2, 22, 2)",3,"(squidsz16, squidsz24, squidsz22)"
25,18524813889,31,"(7, 24)",2,"(squidsz11, squidsz14)"
26,17629721826,27,"(3, 2, 22)",3,"(squidsz41, squidsz42, squidsz13)"
27,13136305928,27,"(3, 22, 2)",3,"(squidsz01, squidsz10, squidsz03)"
28,17586851595,71,"(19, 19, 2, 7, 24)",5,"(squidsz12, squidsz67, squidsz18, squidsz33, s..."
33,17520318696,43,"(15, 2, 2, 2, 22)",5,"(squidsz69, squidsz71, squidsz36, squidsz39, s..."
37,13173905695,46,"(21, 25)",2,"(squidsz50, squidsz36)"
42,15515666682,35,"(7, 6, 22)",3,"(squidsz85, squidsz87, squidsz45)"
52,13131673087,53,"(5, 6, 2, 7, 6, 2, 25)",7,"(squidsz15, squidsz22, squidsz19, squidsz31, s..."
56,17620606061,37,"(15, 22)",2,"(squidsz71, squidsz64)"
59,15641403063,46,"(21, 25)",2,"(squidsz30, squidsz83)"
60,17640094887,52,"(15, 15, 22)",3,"(squidsz26, squidsz12, squidsz62)"
64,13110973856,37,"(15, 22)",2,"(squidsz21, squidsz66)"
65,13143340908,33,"(7, 2, 24)",3,"(squidsz02, squidsz06, squidsz20)"
68,15653783544,31,"(7, 2, 22)",3,"(squidsz09, squidsz12, squidsz13)"
71,17658603459,59,"(8, 6, 7, 6, 6, 7, 6, 7, 4, 2)",10,"(squidsz73, squidsz47, squidsz05, squidsz48, s..."
73,13261685155,68,"(7, 7, 9, 12, 6, 7, 7, 7, 6)",9,"(squidsz87, squidsz44, squidsz07, squidsz13, s..."
78,17682498323,44,"(15, 2, 2, 3, 22)",5,"(squidsz61, squidsz77, squidsz78, squidsz75, s..."
81,17600202479,40,"(17, 23)",2,"(squidsz48, squidsz70)"
83,18575939342,59,"(10, 2, 8, 2, 29, 8)",6,"(squidsz68, squidsz26, squidsz31, squidsz75, s..."
93,18617072787,33,"(8, 23, 2)",3,"(squidsz30, squidsz37, squidsz34)"
94,17681101870,27,"(4, 23)",2,"(squidsz22, squidsz31)"
96,15656095523,52,"(15, 15, 22)",3,"(squidsz28, squidsz15, squidsz03)"
97,13205818187,37,"(15, 22)",2,"(squidsz26, squidsz90)"
...,...,...,...,...,...
484,13183481129,41,"(2, 17, 22)",3,"(squidsz20, squidsz24, squidsz49)"
488,15566671223,87,"(3, 2, 15, 15, 15, 34, 3)",7,"(squidsz88, squidsz90, squidsz19, squidsz03, s..."
490,15585819425,55,"(30, 25)",2,"(squidsz14, squidsz69)"
492,18630206082,57,"(5, 15, 15, 22)",4,"(squidsz70, squidsz10, squidsz73, squidsz34)"
505,15633770990,37,"(7, 6, 24)",3,"(squidsz16, squidsz21, squidsz82)"
520,15601092016,79,"(7, 8, 7, 7, 9, 6, 6, 9, 7, 11, 2)",11,"(squidsz20, squidsz09, squidsz87, squidsz70, s..."
534,13191985432,39,"(2, 7, 30)",3,"(squidsz42, squidsz86, squidsz44)"
536,13173511137,37,"(15, 22)",2,"(squidsz41, squidsz03)"
551,15577642909,49,"(23, 26)",2,"(squidsz16, squidsz42)"
554,18586835273,38,"(2, 7, 7, 22)",4,"(squidsz40, squidsz30, squidsz36, squidsz09)"
555,18681187010,28,"(6, 22)",2,"(squidsz48, squidsz02)"
562,18593160629,40,"(7, 2, 7, 2, 22)",5,"(squidsz26, squidsz35, squidsz70, squidsz09, s..."
568,18631897051,28,"(4, 23, 1)",3,"(squidsz04, squidsz26, squidsz08)"
583,18629516524,37,"(15, 22)",2,"(squidsz49, squidsz48)"
594,17638345009,73,"(7, 7, 7, 7, 8, 7, 8, 22)",8,"(squidsz20, squidsz87, squidsz49, squidsz31, s..."
598,18582593817,29,"(7, 22)",2,"(squidsz01, squidsz16)"
608,13011584155,69,"(9, 3, 25, 32)",4,"(squidsz42, squidsz13, squidsz82, squidsz26)"
614,18683806286,69,"(27, 42)",2,"(squidsz63, squidsz76)"
616,13227727630,29,"(22, 7)",2,"(squidsz46, squidsz79)"
620,18647511109,65,"(7, 2, 56)",3,"(squidsz73, squidsz78, squidsz81)"
621,17600439098,77,"(10, 7, 7, 8, 6, 8, 15, 8, 6, 2)",10,"(squidsz88, squidsz25, squidsz29, squidsz73, s..."
633,13278676127,35,"(3, 3, 27, 2)",4,"(squidsz24, squidsz37, squidsz86, squidsz32)"
648,18665009230,47,"(5, 2, 2, 38)",4,"(squidsz21, squidsz39, squidsz35, squidsz84)"
655,17677131251,6,"(3, 1, 2)",3,"(squidsz88, squidsz15, squidsz43)"
656,13014271855,25,"(3, 22)",2,"(squidsz64, squidsz06)"
657,18666740667,28,"(6, 22)",2,"(squidsz66, squidsz05)"
659,13208153720,9,"(7, 1, 1)",3,"(squidsz72, squidsz76, squidsz77)"
670,13255692959,29,"(3, 2, 2, 22)",4,"(squidsz13, squidsz23, squidsz27, squidsz42)"
673,15685291014,6,"(2, 2, 2)",3,"(squidsz35, squidsz37, squidsz88)"
676,17608225135,6,"(2, 2, 2)",3,"(squidsz69, squidsz03, squidsz13)"

#### 查看这些客户当日是否有其他返回码的请求

In [52]:
data=db_conn.sid_info.find({"end_time":{'$gte':date_to_time(BEGIN_DATE),'$lte':date_to_time(END_DATE)},'tel':{'$in':tmp_3.tel.values.tolist()}})
data2=list(data)
data2=pd.DataFrame(x for x in data2)
some_sid_http_proxy=get_proxy(data2)
some_sid_http_proxy_pd=pd.DataFrame(x for x in some_sid_http_proxy) 
some_sid_http_proxy_pd=get_new_tel_list(some_sid_http_proxy_pd)

In [53]:
some_sid_http_proxy_pd

,http_req_count,http_unique,http_unique_count,req_count,tel
0,"(3, 1, 1, 1)","(squidsz13, squidsz29, squidsz71, squidsz64)",4,6,13001133322
1,"(3, 22)","(squidsz29, squidsz75)",2,25,13007944252
2,"(32, 9, 3, 25)","(squidsz26, squidsz42, squidsz13, squidsz82)",4,69,13011584155
3,"(3, 22)","(squidsz64, squidsz06)",2,25,13014271855
4,"(25, 21)","(squidsz40, squidsz50)",2,46,13017860186
5,"(24, 19, 20)","(squidsz88, squidsz62, squidsz16)",3,63,13032414471
6,"(3, 3, 25, 3, 2)","(squidsz28, squidsz74, squidsz78, squidsz34, s...",5,36,13042995501
7,"(2, 22, 7)","(squidsz71, squidsz73, squidsz34)",3,31,13062711531
8,"(7, 25, 6, 35)","(squidsz86, squidsz48, squidsz89, squidsz12)",4,73,13071909732
9,"(22, 15)","(squidsz31, squidsz83)",2,37,13081002200
10,"(7, 7, 2, 2, 2, 22)","(squidsz09, squidsz16, squidsz18, squidsz12, s...",6,42,13099386799
11,"(22, 15, 15, 3, 2)","(squidsz41, squidsz45, squidsz61, squidsz30, s...",5,57,13099910323
12,"(20, 15)","(squidsz82, squidsz45)",2,35,13107691616
13,"(7, 20)","(squidsz01, squidsz04)",2,27,13109938236
14,"(22, 15)","(squidsz66, squidsz21)",2,37,13110973856
15,"(25, 22)","(squidsz10, squidsz40)",2,47,13112529298
16,"(5, 6, 2, 7, 6, 2, 25)","(squidsz15, squidsz22, squidsz19, squidsz31, s...",7,53,13131673087
17,"(3, 22, 2)","(squidsz01, squidsz10, squidsz03)",3,27,13136305928
18,"(7, 2, 24)","(squidsz02, squidsz06, squidsz20)",3,33,13143340908
19,"(22, 15)","(squidsz08, squidsz19)",2,37,13155512382
20,"(2, 2, 2)","(squidsz33, squidsz35, squidsz36)",3,6,13169115447
21,"(25, 21)","(squidsz69, squidsz03)",2,46,13169867832
22,"(22, 15)","(squidsz03, squidsz41)",2,37,13173511137
23,"(25, 21)","(squidsz36, squidsz50)",2,46,13173905695
24,"(3, 2, 2, 23)","(squidsz76, squidsz79, squidsz81, squidsz88)",4,30,13178164789
25,"(7, 22, 2)","(squidsz43, squidsz67, squidsz64)",3,31,13181515359
26,"(22, 2, 17)","(squidsz49, squidsz20, squidsz24)",3,41,13183481129
27,"(7, 2, 30)","(squidsz86, squidsz42, squidsz44)",3,39,13191985432
28,"(23, 17)","(squidsz29, squidsz38)",2,40,13194996636
29,"(22, 15)","(squidsz90, squidsz26)",2,37,13205818187
...,...,...,...,...,...
117,"(7, 2, 7, 2, 22)","(squidsz26, squidsz35, squidsz70, squidsz09, s...",5,40,18593160629
118,"(3, 22, 15)","(squidsz02, squidsz09, squidsz25)",3,40,18595193113
119,"(22, 2)","(squidsz81, squidsz77)",2,24,18603726186
120,"(7, 2, 2, 25)","(squidsz41, squidsz44, squidsz46, squidsz39)",4,36,18607881658
121,"(8, 23, 2)","(squidsz30, squidsz37, squidsz34)",3,33,18617072787
122,"(22, 16)","(squidsz29, squidsz31)",2,38,18621566497
123,"(22, 15, 7, 2, 18)","(squidsz48, squidsz49, squidsz09, squidsz12, s...",5,64,18629516524
124,"(22, 15, 5, 15)","(squidsz34, squidsz73, squidsz70, squidsz10)",4,57,18630206082
125,"(4, 23, 1)","(squidsz04, squidsz26, squidsz08)",3,28,18631897051
126,"(7, 22)","(squidsz69, squidsz02)",2,29,18637110454
127,"(22, 19)","(squidsz37, squidsz68)",2,41,18642891671
128,"(56, 7, 2)","(squidsz81, squidsz73, squidsz78)",3,65,18647511109
129,"(22, 3, 2)","(squidsz20, squidsz11, squidsz14)",3,27,18650166700
130,"(22, 15)","(squidsz85, squidsz24)",2,37,18650485285
131,"(6, 8, 7, 9, 22)","(squidsz15, squidsz23, squidsz36, squidsz89, s...",5,52,18658030904
132,"(22, 15)","(squidsz88, squidsz19)",2,37,18658622158
133,"(3, 22, 15)","(squidsz12, squidsz18, squidsz28)",3,40,18659753520
134,"(7, 22)","(squidsz83, squidsz88)",2,29,18659817112
135,"(22, 15)","(squidsz21, squidsz34)",2,37,18664433781
136,"(5, 2, 38, 2)","(squidsz21, squidsz39, squidsz84, squidsz35)",4,47,18665009230
137,"(6, 22)","(squidsz66, squidsz05)",2,28,18666740667
138,"(22, 3)","(squidsz32, squidsz26)",2,25,18677929025
139,"(4, 22)","(squidsz07, squidsz19)",2,26,18680289959
140,"(6, 22)","(squidsz48, squidsz02)",2,28,18681187010
141,"(7, 22, 2)","(squidsz77, squidsz86, squidsz85)",3,31,18681689986
142,"(42, 27)","(squidsz76, squidsz63)",2,69,18683806286
143,"(22, 15, 4, 15, 2)","(squidsz78, squidsz47, squidsz04, squidsz23, s...",5,58,18687353511
144,"(3, 2, 3, 22)","(squidsz12, squidsz14, squidsz16, squidsz26)",4,30,18688911118
145,"(25, 26)","(squidsz26, squidsz29)",2,51,18690971636
146,"(22, 16)","(squidsz37, squidsz05)",2,38,18691452752

#### 这些用户当日不存在其他请求，由此推测可能是频繁变更IP地址引起封禁

### C、分析请求数量超过100的代理

In [54]:
filte=np.logical_and(new_tel_pd.http_unique_count.values>1,new_tel_pd.req_count.values>100)
tmp_4=new_tel_pd.loc[filte,['tel','req_count','http_req_count','http_unique_count','http_unique']]
tmp_4

,tel,req_count,http_req_count,http_unique_count,http_unique
104,18621265154,114,"(17, 17, 18, 18, 4, 17, 23)",7,"(squidsz68, squidsz02, squidsz28, squidsz04, s..."
457,13073635376,115,"(46, 42, 27)",3,"(squidsz62, squidsz88, squidsz16)"

#### 使用代理数量相对B情况要少，但是均存在某一个代理使用超过100的情况，可能是因为当日请求量超过阈值或者Ip地址发送变化引起

### D、分析C中代理使用量超过100的情况发生的时机

In [55]:
def select_tel(tel):
    data=db_conn.sid_info.find({"end_time":{'$gte':date_to_time(BEGIN_DATE),'$lte':date_to_time(END_DATE)},'tel':tel})
    data2=list(data)
    data2=pd.DataFrame(x for x in data2)
    some_sid_http_proxy=get_proxy(data2)
    some_sid_http_proxy_pd=pd.DataFrame(x for x in some_sid_http_proxy) 
    some_sid_http_proxy_pd=some_sid_http_proxy_pd.loc[some_sid_http_proxy_pd.req_count.values>0,['sid','req_count','tel','status','dates']]
    some_sid_http_proxy_pd['dates']=some_sid_http_proxy_pd.dates.map(max)
    return some_sid_http_proxy_pd

In [59]:
select_tel('18621265154').sort_values(by="dates")

,sid,req_count,tel,status,dates
0,SIDd6038b2f47164f2e990fde5c3bbb41e2,23,18621265154,5017,20181004221310
1,SIDfcc4522b534e48cda62620ee02a6fc27,21,18621265154,5017,20181004221913
2,SIDa87087191fbe4e9ea0345ddb18cc647a,18,18621265154,5017,20181004222318
3,SID22f190a1fa7d49febd294a8a59995d50,18,18621265154,5017,20181004222948
4,SID50b9d0bac9694ef2b55a7b69d3fd1ba7,17,18621265154,5017,20181004223827
5,SIDfa5c738402d644e4a9bfb2f740c6c020,17,18621265154,5017,20181004225727

In [60]:
select_tel('13073635376').sort_values(by="dates")

,sid,req_count,tel,status,dates
0,SIDd559e3a0febe48f69591ec87446c6292,27,13073635376,5017,20181004190015
1,SID2595543a5bd548b4be1ac77f62938d80,42,13073635376,5017,20181004191009
2,SID9e8129f2851543319b4dac4578059560,46,13073635376,5017,20181004191610

#### 由此可以看出，在首次请求时已经触发封禁

## 5、结论
### 1）、单次爬虫事务中，如果短时间内请求官网超过20次，可能被封禁
### 2）、多次爬虫事务中，如果使用多个ip代理请求官网，超过2个ip将可能被封禁
### 3）、联通反爬策略为，ip总请求次数超过3000，可能被封禁

# 6、采样爬取成功的联通，分析

In [75]:
data=db_conn.sid_info.find({"end_time":{'$gte':date_to_time(BEGIN_DATE),'$lte':date_to_time(END_DATE)},'status':0,'crawler_channel':{'$exists':False},'tel_info.flow_type':'10010'}).limit(40)
data2=list(data)
data2=pd.DataFrame(x for x in data2)
some_sid_http_proxy=get_proxy(data2)
some_sid_http_proxy_pd=pd.DataFrame(x for x in some_sid_http_proxy) 
some_sid_http_proxy_pd=get_new_tel_list(some_sid_http_proxy_pd)

In [76]:
some_sid_http_proxy_pd

,http_req_count,http_unique,http_unique_count,req_count,tel
0,"(129,)","(squidsz18,)",1,129,18276128269
1,"(24,)","(squidsz16,)",1,24,18986010584
2,"(21,)","(squidsz22,)",1,21,17311387864
3,"(52,)","(squidsz19,)",1,52,18776702373
4,"(9,)","(squidsz21,)",1,9,15339633070
5,"(6, 12)","(squidsz20, squidsz09)",2,18,13566797697
6,"(58,)","(squidsz15,)",1,58,13788019300
7,"(36,)","(squidsz12,)",1,36,13623164303
8,"(20,)","(squidsz07,)",1,20,18881848883
9,"(20, 4)","(squidsz11, squidsz04)",2,24,18483135858
10,"(19,)","(squidsz66,)",1,19,18580039838
11,"(21,)","(squidsz08,)",1,21,15320001652
12,"(6,)","(squidsz14,)",1,6,15968159312
13,"(16,)","(squidsz64,)",1,16,13180628460
14,"(46,)","(squidsz06,)",1,46,15277340234
15,"(97,)","(squidsz90,)",1,97,13977814900
16,"(18,)","(squidsz01,)",1,18,13667364403
17,"(19,)","(squidsz87,)",1,19,17339333601
18,"(20,)","(squidsz62,)",1,20,15683385027
19,"(22,)","(squidsz61,)",1,22,13172462334
20,"(4,)","(squidsz89,)",1,4,18774485617
21,"(11, 13)","(squidsz88, squidsz86)",2,24,15833458913
22,"(18,)","(squidsz85,)",1,18,18390302801
23,"(53,)","(squidsz84,)",1,53,13988999289
24,"(22,)","(squidsz79,)",1,22,13625792205
25,"(5,)","(squidsz50,)",1,5,13102362571
26,"(7, 19, 2)","(squidsz44, squidsz48, squidsz47)",3,28,15639195579
27,"(23,)","(squidsz82,)",1,23,13669494439
28,"(32,)","(squidsz45,)",1,32,18575107371
29,"(22,)","(squidsz73,)",1,22,15882951824
30,"(9, 133)","(squidsz81, squidsz39)",2,142,18277165138
31,"(18,)","(squidsz71,)",1,18,18390992397
32,"(14,)","(squidsz75,)",1,14,13983077008
33,"(2, 26)","(squidsz36, squidsz38)",2,28,18070506321
34,"(7, 2, 35)","(squidsz32, squidsz37, squidsz42)",3,44,18685114645
35,"(176,)","(squidsz35,)",1,176,13737371192
36,"(11,)","(squidsz37,)",1,11,13668479396

In [77]:
filte=np.logical_and(some_sid_http_proxy_pd.http_unique_count.values>1,True)
tmp_5=some_sid_http_proxy_pd.loc[filte,['tel','req_count','http_req_count','http_unique_count','http_unique']]
tmp_5

,tel,req_count,http_req_count,http_unique_count,http_unique
5,13566797697,18,"(6, 12)",2,"(squidsz20, squidsz09)"
9,18483135858,24,"(20, 4)",2,"(squidsz11, squidsz04)"
21,15833458913,24,"(11, 13)",2,"(squidsz88, squidsz86)"
26,15639195579,28,"(7, 19, 2)",3,"(squidsz44, squidsz48, squidsz47)"
30,18277165138,142,"(9, 133)",2,"(squidsz81, squidsz39)"
33,18070506321,28,"(2, 26)",2,"(squidsz36, squidsz38)"
34,18685114645,44,"(7, 2, 35)",3,"(squidsz32, squidsz37, squidsz42)"